Repository Farhan-Faisal/drift_nw, pull requests merged in 2025-01, with the labels that each got.

#1 Backend init
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/config/index.ts
  backend/src/routes/index.ts
  backend/tsconfig.json
Labels: enhancement

#2 frontend map added
  Drift/app/(tabs)/index.tsx
  Drift/components/VancouverMap.tsx
  Drift/components/atoms/BusIcon.tsx
  Drift/components/organisms/VancouverMap.tsx
  Drift/components/utils/route_utils.tsx
Labels: enhancement, feature

#9 connected to jiayi
  frontend/app/(tabs)/index.tsx
  frontend/components/organisms/VancouverMap.tsx
  frontend/components/utils/payment.tsx
  frontend/context/ParamsContext.tsx
Labels: enhancement

#10 connected to stripe
  frontend/app/(tabs)/_layout.tsx
  frontend/app/(tabs)/index.tsx
  frontend/app/(tabs)/payment.tsx
  frontend/app/index.tsx
  frontend/components/organisms/VancouverMap.tsx
  frontend/context/ParamsContext.tsx
Labels: enhancement

#11 add documenttaion
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  frontend/app/(tabs)/_layout.tsx
  frontend/app/(tabs)/explore.tsx
  frontend/app/index.tsx
Labels: documentation
